version: '3'

services:
  nextjs:
    build: .
    command: ['yarn', 'dev']
    ports:
      - '3000:3000'
    volumes:
      - ./nextjs:/app
      - node_modules_volume:/app/node_modules

volumes:
  node_modules_volume:
