version: '3'

services:
  nextjs:
    build: .
    command: ['yarn', 'dev']
    ports:
      - '3000:3000'
    volumes:
      - ./nextjs:/app
      - node_modules_volume:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true #ホットリロード有効化

volumes:
  node_modules_volume:
